version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    versioning-strategy: increase-if-necessary
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
