language: node_js
node_js:
- 4.2
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: eb35oCSXGMNIF7xGeoBa0m0O68Eoc5iXJV8INTRETMkmVWhpBHMDpXsbMIgsNG0quGKB8O0IYmFIXgaDv5asBVzLqCcOsCoRoDeyD7sepc+rq68/O3dZ9BWClsvy9onGuQ8kiWaJRriWBHoFBbvb8Zto1+l4ZJvOuO4zWl/1faY=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- npm install -g grunt-cli
- pip install -r protocol-examples/python/requirements.txt -t protocol-examples/python
sudo: false
deploy:
  provider: npm
  email: jononor@gmail.com
  api_key:
    secure: eWJlg7JOHeVt97oztFdNcdCMRSeL1uYfubG4IgdPeDfnLfmBWRhbVBbFR0GRephZhW2621vzfHgR92S3fxwZmD6t9WfABnU8ZHdowTrxty+0oN4PlXO6jkPMQP22kcfs2cTnJs/eMrDjDz5ddTcFFeDZLuNC9XjAKQS6gjwALCg=
  on:
    tags: true
    repo: flowbased/fbp-spec
after_deploy:
- grunt gh-pages
